### ISSUE TITLE
`nico.nim(2227, 19) Error: type mismatch: got '(int, int, int32, int32)' for '(int(x), int(y), src.w * scale, src.h * scale)' but expected 'Rect = tuple[x: int, y: int, w: int, h: int]'`

### ISSUE THREAD

**Issue by arkanoid87** [ftsf/nico#121]
```
choosenim stable
nimble install nico
nicoboot test test test
cd test
nimble webd
```

**Comment by HVukman** [comment]
Have the same problem with Nim2.0

**Comment by HVukman** [comment]
Can build now with webr on Ubuntu, but I cannot run it in the browser:

registerOrRemoveHandler: the target element for event handler registration does not exist, when processing the following event handler 
registration:Object
allowsDeferredCalls: true
callbackfunc: 609
eventTypeString: "touchstart"
handlerFunc: e=> {…}
target: null
useCapture: 0
[[Prototype]]: Object

and then:

Aborted(Runtime error: The application has corrupted its heap memory area (address zero)!)
abort @ niconim.js:1
Uncaught RuntimeError: Aborted(Runtime error: The application has corrupted its heap memory area (address zero)!)
    at abort (niconim.js:1:20947)
    at checkStackCookie (niconim.js:1:17381)
    at handleException (niconim.js:1:99085)
    at callUserCallback (niconim.js:1:118954)
    at Object.runIter (niconim.js:1:129885)
    at Browser_mainLoop_runner (niconim.js:1:128289)

**Comment by HVukman** [comment]
^ This works under WIndows, thanks.

**Comment by ayukoid** [comment]
@HVukman Doesn't work for me on windows :(
![image](https://github.com/user-attachments/assets/63491889-a65a-4db8-ba9f-5bc87eb7f9c9)
